### ISSUE TITLE
error during plugin installation

### ISSUE THREAD

**Issue by luciano-nascimento** [godrix/insomnia-plugin-dracula-soft-theme#1]
insomnia version: 2020.4.2

![image](https://user-images.githubusercontent.com/7797878/100094579-01e89c80-2e38-11eb-9c4c-559fb4b46d8c.png)

**Comment by godrix** [comment]
Hello, I imagine you are using some linux, right? the error is because it is not finding `libX11.so.6`. googlers should solve your problem

**Comment by luciano-nascimento** [comment]
Hi ! It's already installed ! Once it's not about Insomnia, I will keep searching about this error on my system. Thank you.
